### ISSUE TITLE
jsons parse function unexpected result

### ISSUE THREAD

**Issue by remizovm** [go-gophers/gophers#20]
Hello. I'm trying to encode unix timestamp as a son field and the parse function treats it as a float64. Attached a source file which reproduces the problem.  
[main.go.zip](https://github.com/go-gophers/gophers/files/422188/main.go.zip)

**Comment by AlekSi** [comment]
Code from archive:

``` go
package main

import (
    "fmt"
    "time"

    "github.com/go-gophers/gophers/jsons"
)

func main() {
    dt := time.Now().Unix()
    good := fmt.Sprintf(`{"test":%d}`, dt)
    bad := jsons.Parse(`{"test":%d}`, dt)
    fmt.Printf("good:%s bad:%s\n", good, bad)
}
```

**Comment by AlekSi** [comment]
That's how [encoding/json](https://golang.org/pkg/encoding/json/#Unmarshal) works. JSON doesn't really have integers.

**Comment by remizovm** [comment]
Well, that does not really solve my problem. Maybe you should take a look at json's package [UseNumber](https://golang.org/pkg/encoding/json/#Decoder.UseNumber) function? It does the trick and unixtime unmarshalls correctly. Right now I'm forced to modify your code to fix this.
